import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF4E2FF',
    },
    backButton: {
        position: 'absolute',
        top: 40,
        left: 16,
        zIndex: 10,
        backgroundColor: '#FFA729',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loaderContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFF',
    },
    cards: {
        marginLeft: 20,
    },
    loaderText: {
        marginTop: 10,
        color: '#555',
        fontSize: 16,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#FFF',
    },
    errorText: {
        fontSize: 18,
        color: 'red',
        textAlign: 'center',
    },
    errorButton: {
        marginTop: 20,
        backgroundColor: '#FFA729',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    errorButtonText: {
        color: '#FFF',
        fontSize: 16,
    },
    info: {
        paddingTop: 100,
        borderBottomWidth: 1,
        borderColor: '#f49600',
        padding: 16,
        alignItems: 'center',
        backgroundColor: '#FFF4E2',
        marginBottom: 16,
    },
    title: {
        fontSize: 40,
        fontWeight: 'bold',
        color: '#FFA729',
        marginBottom: 15,
    },
    description: {
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 15,
        color: '#555',
    },
    address: {
        fontSize: 14,
        color: '#555',
    },
    seats: {
        fontSize: 14,
        color: '#555',
    },
    withLaptop: {
        fontSize: 14,
        color: '#555',
    },
    withDog: {
        fontSize: 14,
        color: '#555',
    },
    rating: {
        fontSize: 14,
        color: '#fd9d00',
        marginBottom: 16,
        marginTop: 20,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFA729',
        marginHorizontal: 20,
        marginVertical: 15,
    },
    card: {
        width: 150,
        height: 100,
        justifyContent: 'center',
        marginHorizontal: 8,
        backgroundColor: '#ffffff',
        borderRadius: 8,
        padding: 8,
        alignItems: 'center',
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#FFA729',
    },
    cardPrice: {
        fontSize: 14,
        color: '#555',
    },
    // review: {
    //     marginHorizontal: 16,
    //     marginVertical: 8,
    //     padding: 16,
    //     backgroundColor: '#FFF4E2',
    //     borderRadius: 8,
    // },
    reviewName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFA729',
    },
    reviewText: {
        fontSize: 14,
        color: '#555',
        marginVertical: 8,
    },
    reviewRating: {
        fontSize: 14,
        color: '#888',
    },
    reviews: {
        marginHorizontal: 16,
        marginVertical: 8,
    },
    review: {
        backgroundColor: '#ffffff',
        borderRadius: 8,
        padding: 16,
        marginVertical: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    reviewDate: {
        fontSize: 12,
        color: '#888',
        marginBottom: 8,
    },

    reviewScore: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#FFA729',
    },
    noReviewsText: {
        fontSize: 14,
        color: '#555',
        textAlign: 'center',
        marginVertical: 16,
    },
    likeButton: {
        position: 'absolute',
        top: 20,
        marginTop: 20,
        right: 16,
        zIndex: 10,
    },

    addReviewButton: {
        position: 'absolute',
        bottom: 16,
        left: 16,
        right: 16,
        backgroundColor: '#FFA729',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    addReviewButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 16,
    },
    reviewInputContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#F8F8F8',
        borderTopWidth: 1,
        borderColor: '#E0E0E0',
        padding: 16,
    },
    reviewInput: {
        height: 80,
        borderColor: '#CCC',
        borderWidth: 1,
        borderRadius: 8,
        padding: 8,
        marginBottom: 8,
        backgroundColor: '#FFF',
    },
    reviewScoreInput: {
        height: 40,
        borderColor: '#CCC',
        borderWidth: 1,
        borderRadius: 8,
        padding: 8,
        marginBottom: 8,
        backgroundColor: '#FFF',
    },
    submitButton: {
        height: 40,
        backgroundColor: '#FFA729',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    submitButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
    },
});

export default styles;
