import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFF4E2',
    },
    backButton: {
        position: 'absolute',
        top: 40,
        left: 16,
        zIndex: 10,
        backgroundColor: '#FFA729',
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    info: {
        padding: 16,
        alignItems: 'center',
        backgroundColor: '#FFF4E2',
        marginBottom: 16,
    },
    title: {
        marginTop: 100,
        fontSize: 40,
        fontWeight: 'bold',
        color: '#FFA729',
        marginBottom: 15,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#FFA729',
        marginHorizontal: 16,
        marginVertical: 8,
    },
    ingredients: {
        marginHorizontal: 16,
        marginBottom: 16,
        padding: 16,
        backgroundColor: '#ffffff',
        borderRadius: 8,
    },
    ingredientText: {
        fontSize: 16,
        color: '#555',
    },
    card: {
        width: 150,
        marginHorizontal: 8,
        backgroundColor: '#FFF4E2',
        borderRadius: 8,
        padding: 8,
        alignItems: 'center',
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#FFA729',
    },
    cardAddress: {
        fontSize: 14,
        color: '#555',
    },
    review: {
        marginHorizontal: 16,
        marginVertical: 8,
        padding: 16,
        backgroundColor: '#ffffff',
        borderRadius: 8,
    },
    button: {
        marginHorizontal: 16,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFA729',
        borderRadius: 8,
        padding: 10,
        marginVertical: 10,
    },
    reviewName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFA729',
    },
    reviewText: {
        fontSize: 14,
        color: '#555',
        marginVertical: 8,
    },
    reviewRating: {
        fontSize: 14,
        color: '#888',
    },
    ratingText: {
        fontSize: 16,
        marginLeft: 20,
    },
    likeButton: {
        position: 'absolute',
        top: 20,
        right: 16,
        zIndex: 10,
        marginTop: 20,
    },
    addReviewButton: {
        position: 'absolute',
        bottom: 16,
        left: 16,
        right: 16,
        backgroundColor: '#FFA729',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    addReviewButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
        fontSize: 16,
    },
    reviewInputContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#F8F8F8',
        borderTopWidth: 1,
        borderColor: '#E0E0E0',
        padding: 16,
    },
    reviewInput: {
        height: 80,
        borderColor: '#CCC',
        borderWidth: 1,
        borderRadius: 8,
        padding: 8,
        marginBottom: 8,
        backgroundColor: '#FFF',
    },
    reviewScoreInput: {
        height: 40,
        borderColor: '#CCC',
        borderWidth: 1,
        borderRadius: 8,
        padding: 8,
        marginBottom: 8,
        backgroundColor: '#FFF',
    },
    submitButton: {
        height: 40,
        backgroundColor: '#FFA729',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    submitButtonText: {
        color: '#FFF',
        fontWeight: 'bold',
    },
});

export default styles;
